export interface SymbolEntry {
  sym: string;
  name: string;
}

export const SP500_TOP100: SymbolEntry[] = [
  { sym: "AAPL",  name: "Apple Inc." },
  { sym: "MSFT",  name: "Microsoft Corp." },
  { sym: "NVDA",  name: "NVIDIA Corp." },
  { sym: "GOOGL", name: "Alphabet Inc. A" },
  { sym: "AMZN",  name: "Amazon.com Inc." },
  { sym: "META",  name: "Meta Platforms Inc." },
  { sym: "BRK.B", name: "Berkshire Hathaway B" },
  { sym: "TSLA",  name: "Tesla Inc." },
  { sym: "GOOG",  name: "Alphabet Inc. C" },
  { sym: "AVGO",  name: "Broadcom Inc." },
  { sym: "JPM",   name: "JPMorgan Chase & Co." },
  { sym: "V",     name: "Visa Inc." },
  { sym: "LLY",   name: "Eli Lilly & Co." },
  { sym: "UNH",   name: "UnitedHealth Group" },
  { sym: "XOM",   name: "Exxon Mobil Corp." },
  { sym: "MA",    name: "Mastercard Inc." },
  { sym: "JNJ",   name: "Johnson & Johnson" },
  { sym: "PG",    name: "Procter & Gamble Co." },
  { sym: "HD",    name: "Home Depot Inc." },
  { sym: "COST",  name: "Costco Wholesale Corp." },
  { sym: "ORCL",  name: "Oracle Corp." },
  { sym: "ABBV",  name: "AbbVie Inc." },
  { sym: "CRM",   name: "Salesforce Inc." },
  { sym: "BAC",   name: "Bank of America Corp." },
  { sym: "CVX",   name: "Chevron Corp." },
  { sym: "MRK",   name: "Merck & Co. Inc." },
  { sym: "WMT",   name: "Walmart Inc." },
  { sym: "AMD",   name: "Advanced Micro Devices" },
  { sym: "ADBE",  name: "Adobe Inc." },
  { sym: "NFLX",  name: "Netflix Inc." },
  { sym: "KO",    name: "Coca-Cola Co." },
  { sym: "PEP",   name: "PepsiCo Inc." },
  { sym: "WFC",   name: "Wells Fargo & Co." },
  { sym: "LIN",   name: "Linde plc" },
  { sym: "TMO",   name: "Thermo Fisher Scientific" },
  { sym: "MCD",   name: "McDonald's Corp." },
  { sym: "CSCO",  name: "Cisco Systems Inc." },
  { sym: "ABT",   name: "Abbott Laboratories" },
  { sym: "INTU",  name: "Intuit Inc." },
  { sym: "QCOM",  name: "Qualcomm Inc." },
  { sym: "VZ",    name: "Verizon Communications" },
  { sym: "IBM",   name: "International Business Machines" },
  { sym: "DIS",   name: "Walt Disney Co." },
  { sym: "ACN",   name: "Accenture plc" },
  { sym: "GE",    name: "General Electric Co." },
  { sym: "CAT",   name: "Caterpillar Inc." },
  { sym: "AMAT",  name: "Applied Materials Inc." },
  { sym: "TXN",   name: "Texas Instruments Inc." },
  { sym: "MS",    name: "Morgan Stanley" },
  { sym: "NKE",   name: "Nike Inc." },
  { sym: "RTX",   name: "RTX Corp." },
  { sym: "BA",    name: "Boeing Co." },
  { sym: "SPGI",  name: "S&P Global Inc." },
  { sym: "UPS",   name: "United Parcel Service" },
  { sym: "SBUX",  name: "Starbucks Corp." },
  { sym: "DE",    name: "Deere & Co." },
  { sym: "LOW",   name: "Lowe's Companies Inc." },
  { sym: "BMY",   name: "Bristol-Myers Squibb" },
  { sym: "PLD",   name: "Prologis Inc." },
  { sym: "SYK",   name: "Stryker Corp." },
  { sym: "BSX",   name: "Boston Scientific Corp." },
  { sym: "BLK",   name: "BlackRock Inc." },
  { sym: "MDT",   name: "Medtronic plc" },
  { sym: "ADP",   name: "Automatic Data Processing" },
  { sym: "C",     name: "Citigroup Inc." },
  { sym: "SCHW",  name: "Charles Schwab Corp." },
  { sym: "GILD",  name: "Gilead Sciences Inc." },
  { sym: "MO",    name: "Altria Group Inc." },
  { sym: "TMUS",  name: "T-Mobile US Inc." },
  { sym: "AMGN",  name: "Amgen Inc." },
  { sym: "MMC",   name: "Marsh & McLennan" },
  { sym: "PFE",   name: "Pfizer Inc." },
  { sym: "HON",   name: "Honeywell International" },
  { sym: "AXP",   name: "American Express Co." },
  { sym: "MU",    name: "Micron Technology Inc." },
  { sym: "ETN",   name: "Eaton Corp." },
  { sym: "GS",    name: "Goldman Sachs Group" },
  { sym: "PYPL",  name: "PayPal Holdings Inc." },
  { sym: "INTC",  name: "Intel Corp." },
  { sym: "LRCX",  name: "Lam Research Corp." },
  { sym: "ELV",   name: "Elevance Health Inc." },
  { sym: "UBER",  name: "Uber Technologies Inc." },
  { sym: "NOW",   name: "ServiceNow Inc." },
  { sym: "T",     name: "AT&T Inc." },
  { sym: "NEE",   name: "NextEra Energy Inc." },
  { sym: "CMCSA", name: "Comcast Corp." },
  { sym: "DHR",   name: "Danaher Corp." },
  { sym: "SRE",   name: "Sempra Energy" },
  { sym: "KLAC",  name: "KLA Corp." },
  { sym: "ADI",   name: "Analog Devices Inc." },
  { sym: "ITW",   name: "Illinois Tool Works" },
  { sym: "PANW",  name: "Palo Alto Networks Inc." },
  { sym: "ICE",   name: "Intercontinental Exchange" },
  { sym: "FDX",   name: "FedEx Corp." },
  { sym: "REGN",  name: "Regeneron Pharmaceuticals" },
  { sym: "CI",    name: "Cigna Group" },
  { sym: "MDLZ",  name: "Mondelez International" },
  { sym: "WM",    name: "Waste Management Inc." },
  { sym: "SHW",   name: "Sherwin-Williams Co." },
  { sym: "APH",   name: "Amphenol Corp." },
  { sym: "ZTS",   name: "Zoetis Inc." },
];
